### ISSUE TITLE
ws_copy_policy tool throws unhandled exceptions

### ISSUE THREAD

**Issue by wssbanana** [whitesource-ps/ws-copy-policy#24]
Hi team, hope you are doing well, please see behavior below and let me know what can be done to resolve it.

**Bug Description**
Once the connection is established, the tool starts processing but then aborts with an unhandled exception:

ws_copy_policy -u "https://saas-eu.whitesourcesoftware.com/api/v1.3" -k ((removed)) -o ((removed)) -s product
2022-12-06 11:49:53,656 - starting...
2022-12-06 11:49:53,656 - validating parameters
2022-12-06 11:49:53,656 - using url https://saas-eu.whitesourcesoftware.com/api/v1.3
2022-12-06 11:49:54,346 - Start getProductPolicies api
2022-12-06 11:49:54,346 - Start getProductPolicies api
2022-12-06 11:49:54,346 - Start getProductPolicies api
2022-12-06 11:49:54,346 - Start getProductPolicies api
2022-12-06 11:49:54,347 - Start getProductPolicies api
2022-12-06 11:49:54,719 - Start getProductPolicies api
2022-12-06 11:49:54,722 - Start getProductPolicies api
2022-12-06 11:49:54,724 - Start getProductPolicies api
2022-12-06 11:49:54,726 - Start getProductPolicies api
2022-12-06 11:49:54,764 - Start getProductPolicies api
2022-12-06 11:49:55,122 - Start getProductPolicies api
2022-12-06 11:49:55,139 - Start getProductPolicies api
2022-12-06 11:49:55,141 - Start getProductPolicies api
2022-12-06 11:49:55,143 - Start getProductPolicies api
2022-12-06 11:49:55,169 - The group of reassign_vulerability reassign action policy was removed from the organization - the policy will not be copied
2022-12-06 11:49:55,169 - Start getProductPolicies api
2022-12-06 11:49:55,444 - Start getProductPolicies api
2022-12-06 11:49:55,541 - Start getProductPolicies api
2022-12-06 11:49:55,545 - Start getProductPolicies api
2022-12-06 11:49:55,558 - Start getProductPolicies api
2022-12-06 11:49:55,573 - Start getProductPolicies api
2022-12-06 11:49:55,775 - Start getProductPolicies api
2022-12-06 11:49:55,880 - Start getProductPolicies api
2022-12-06 11:49:55,913 - Start getProductPolicies api
2022-12-06 11:49:55,944 - Start getProductPolicies api
2022-12-06 11:49:55,948 - Start getProductPolicies api
2022-12-06 11:49:56,096 - found destination product: policy-copy-test-dest-product. Key value: ['fdj2aJ4r']
2022-12-06 11:49:56,096 - Start getProductPolicies api
2022-12-06 11:49:56,186 - Start getProductPolicies api
2022-12-06 11:49:56,236 - Start getProductPolicies api
2022-12-06 11:49:56,280 - Start getProductPolicies api
2022-12-06 11:49:56,369 - Start getProductPolicies api
2022-12-06 11:49:56,423 - found source product: policy-copy-test-src-product. Key value: ['fdj2aJ4r']
2022-12-06 11:49:56,423 - Start getProductPolicies api
2022-12-06 11:49:56,719 - Start getProductPolicies api
Traceback (most recent call last):
File "/home/mp/.local/bin/ws_copy_policy", line 8, in <module>
sys.exit(main())
File "/home/mp/.local/lib/python3.10/site-packages/ws_copy_policy/copy_policy.py", line 89, in main
get_policies(conf.org_token, conf.user_key, conf.url, conf.scope, conf.thread)
File "/home/mp/.local/lib/python3.10/site-packages/ws_copy_policy/copy_policy.py", line 115, in get_policies
fill_template_values_and_projects_from_response(scope_tags, template_value_to_policies,
File "/home/mp/.local/lib/python3.10/site-packages/ws_copy_policy/copy_policy.py", line 196, in fill_template_values_and_projects_from_response
thread_pool.starmap(worker, [(scope_item, body, request_type, tag_template_key, template_value_to_policies,
File "/usr/lib/python3.10/multiprocessing/[pool.py](https://pool.py/)", line 375, in starmap
return self._map_async(func, iterable, starmapstar, chunksize).get()
File "/usr/lib/python3.10/multiprocessing/[pool.py](https://pool.py/)", line 774, in get
raise self._value
File "/usr/lib/python3.10/multiprocessing/[pool.py](https://pool.py/)", line 125, in worker
result = (True, func(*args, **kwds))
File "/usr/lib/python3.10/multiprocessing/[pool.py](https://pool.py/)", line 51, in starmapstar
return list(itertools.starmap(args[0], args[1]))
File "/home/mp/.local/lib/python3.10/site-packages/ws_copy_policy/copy_policy.py", line 243, in worker
template_value_to_policies[tags[tag_template_key]] = scope_policies["policies"]
TypeError: unhashable type: 'list'

**Environment Details**  
Python version 3.10.7 on Ubuntu 22.10 Desktop

**Comment by rammatzkvosky** [comment]
Hi @wssbanana 
We fixed this issue.
You can use the[ following version](https://pypi.org/project/ws-copy-policy/23.1.5.3/)
